service: pufouniversity

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

package:
  exclude:
    - tests/**
 
provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.defaultRegion}
  stage: dev${env:SLSUSER, ""}
  environment:
    service: ${self:service}-${self:custom.stage}
    stage: ${self:custom.stage}

custom:
  defaultRegion: eu-west-1
  stage: ${opt:stage, self:provider.stage}
  mastersTable: masters-${self:custom.stage}
  enrolMasterSnsTopicName: enrollMasterEvents-${self:custom.stage}
  enrolMasterSnsTopic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.enrolMasterSnsTopicName}
  defaultVarsStage: dev-user
  vars: ${file(./vars.yml):${opt:stage, self:custom.defaultVarsStage}}
 
functions:
  getMasters:
    handler: src/functions/getMasters.handler
    events:
      - http:
          path: api/masters
          method: get
    environment:
      mastersTable: ${self:custom.mastersTable}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.mastersTable}
      - Effect: Allow
        Action: ssm:GetParameters*
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pufouniversity/*
  
  getMasterDetails:
    handler: src/functions/getMaster.handler
    events:
      - http:
          path: api/master/{id}
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/${self:custom.vars.userPoolId}
    environment:
      mastersTable: ${self:custom.mastersTable}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:query
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.mastersTable}
      - Effect: Allow
        Action: ssm:GetParameters*
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pufouniversity/*

  enrollMaster:
    handler: src/functions/enrollMaster.handler
    events:
      - http:
          path: api/masters
          method: post
    environment:
      enrollMasterSnsTopic: ${self:custom.enrolMasterSnsTopic}
    iamRoleStatements:
      - Effect: Allow
        Action: sns:Publish
        Resource: ${self:custom.enrolMasterSnsTopic}
      - Effect: Allow
        Action: ssm:GetParameters*
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pufouniversity/*

  notifyUniversity:
    handler: src/functions/notifyUniversity.handler
    events:
      - sns: ${self:custom.enrolMasterSnsTopicName}
    environment:
      emailAddress: vgaltes@gmail.com
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - ses:SendEmail
          - ses:SendRawEmail
        Resource: "*"
      - Effect: Allow
        Action: ssm:GetParameters*
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pufouniversity/*

resources:
  - ${file(resources/masters-dynamodb-table.yml)}
  - ${file(resources/cognito-user-pool.yml)}
