service: pufouniversity

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
 
provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.defaultRegion}
  stage: dev${env:SLSUSER, ""}

custom:
  defaultRegion: eu-west-1
  stage: ${opt:stage, self:provider.stage}
  mastersTable: masters-${self:custom.stage}
 
functions:
  getMasters:
    handler: src/functions/getMasters.handler
    events:
      - http:
          path: api/masters
          method: get
    environment:
      mastersTable: ${self:custom.mastersTable}
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.mastersTable}

resources:
  Resources:
    MastersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.mastersTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST